/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void Empezar_click1(GButton source, GEvent event) { //_CODE_:Empezar:866101:
  println("Empezar - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:Empezar:866101:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  Empezar = new GButton(this, 112, 868, 80, 30);
  Empezar.setText("Empezar");
  Empezar.setTextBold();
  Empezar.addEventHandler(this, "Empezar_click1");
  ip = new GLabel(this, 0, 868, 98, 28);
  ip.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  ip.setText("miIp");
  ip.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GButton Empezar; 
GLabel ip; 