/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:txtip:825855:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txtip:825855:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:txtpuerto:380105:
  println("txtpuerto - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:txtpuerto:380105:

public void conectarse(GButton source, GEvent event) { //_CODE_:btnconectar:602704:
  println("btnconectar - GButton >> GEvent." + event + " @ " + millis());
  println(""+txtip.getText()+","+txtpuerto.getText()+"");
  myClient = new Client(this, txtip.getText(),  Integer.valueOf(txtpuerto.getText())); 
  myClient.write("unirse&\n");
  
  //myClient.write(""+txtip.getText()+","+txtpuerto.getText()+"");//169 2017
} //_CODE_:btnconectar:602704:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  txtip = new GTextField(this, 160, 20, 180, 20, G4P.SCROLLBARS_NONE);
  txtip.setText("127.0.0.1");
  txtip.setOpaque(true);
  txtip.addEventHandler(this, "textfield1_change1");
  label1 = new GLabel(this, 200, 0, 100, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Introduce IP");
  label1.setOpaque(true);
  label2 = new GLabel(this, 200, 50, 103, 21);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Introduce Puerto");
  label2.setOpaque(true);
  txtpuerto = new GTextField(this, 160, 70, 180, 20, G4P.SCROLLBARS_NONE);
  txtpuerto.setText("12345");
  txtpuerto.setOpaque(true);
  txtpuerto.addEventHandler(this, "textfield2_change1");
  btnconectar = new GButton(this, 200, 100, 100, 30);
  btnconectar.setText("CONECTARSE");
  btnconectar.addEventHandler(this, "conectarse");
}

// Variable declarations 
// autogenerated do not edit
GTextField txtip; 
GLabel label1; 
GLabel label2; 
GTextField txtpuerto; 
GButton btnconectar; 